#!/bin/bash
# -*- mode: shell-script-mode; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# Copyright (C) 2012-13 O.S. Systems Software LTDA.
# Copyright (C) 2017 Open Source Foundries Ltd.
# Copyright (C) 2020-2026 Toradex AG
# Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
# Adopted to Angstrom:  Khem Raj <raj.khem@gmail.com>
#
# SPDX-License-Identifier: GPL-2.0-only
#

_TDX_BUILDDIR="/build"
BUILDDIR="/build"
export _TDX_BUILDDIR BUILDDIR

if tdx_needs_once /build/conf/local.conf "# Torizon"; then
  sed -i "/^MACHINE .*/c\MACHINE = '$MACHINE'" /build/conf/local.conf
  sed -i "/^DISTRO .*/c\DISTRO = '$DISTRO'" /build/conf/local.conf

  tdx_append_once /build/conf/local.conf "# Torizon" <<EOF
# Where to store sources
DL_DIR = "/build/downloads"

# Where to save shared state
SSTATE_DIR = "/build/sstate-cache"

# Where to save the build system work output
TMPDIR = "/build/tmp"

# Where to save the packages and images
DEPLOY_DIR = "/build/deploy"

# ease up disk space requirements
INHERIT += "rm_work"

# Torizon
include conf/machine/include/\${MACHINE}.inc
EOF
fi

tdx_append_once /build/conf/bblayers.conf "# Torizon" <<EOF
# Torizon
BBLAYERS += "\${TOPDIR}/../work/meta-toradex-torizon"
# Torizon deps
BBLAYERS += "\${TOPDIR}/../work/meta-updater"
BBLAYERS += "\${TOPDIR}/../work/meta-virtualization"
# meta-updater and meta-virtualization deps
BBLAYERS += "\${TOPDIR}/../work/meta-openembedded/meta-filesystems"
BBLAYERS += "\${TOPDIR}/../work/meta-openembedded/meta-python"
BBLAYERS += "\${TOPDIR}/../work/meta-openembedded/meta-networking"

OEROOT := "\${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)))}/../.."
EOF

tdx_print_banner "Common Torizon OS" no
